create table Users (
    id bigint primary key generated by default as identity,
    userName varchar(50) unique,
    passwordHash varchar(100),
    name varchar(30),
    surname varchar(30),
    department varchar(30),
    rank varchar(30),
    email varchar(50) unique,
    photoUrl varchar(400)
);

CREATE TABLE EngineStatus (
    ID bigint primary key generated by default as identity,
    status VARCHAR(50),
    rpm INT,
    temperature FLOAT,
    voltage FLOAT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CoolingSystemStatus (
    ID SERIAL PRIMARY KEY,
    Status VARCHAR(50),
    CoolantTemperature FLOAT,
    SystemPressure FLOAT,
    Timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GeneratorStatus (
    ID SERIAL PRIMARY KEY,
    Status VARCHAR(50),
    Power FLOAT,
    Fuel VARCHAR(50),
    Voltage FLOAT,
    Timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FuelSystemStatus (
    ID SERIAL PRIMARY KEY,
    Status VARCHAR(50) NOT NULL, -- Статус системы (работает, не работает, выведен из строя)
    FuelLevel FLOAT NOT NULL, -- Уровень топлива в процентах (%)
    ContaminantsLevel FLOAT NOT NULL, -- Уровень загрязнителей в топливе (в ppm - parts per million)
    FuelFilterStatus VARCHAR(50) NOT NULL, -- Состояние топливного фильтра (чистый, загрязненный)
    FlowRate FLOAT NOT NULL, -- Расход топлива (в литрах в час или другом измерении)
    LeakDetection BOOLEAN NOT NULL, -- Обнаружение утечек (true, false)
    FuelPumpStatus VARCHAR(50) NOT NULL, -- Статус топливного насоса (работает, не работает, выведен из строя)
    Timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO FuelSystemStatus (Status, FuelLevel, ContaminantsLevel, FuelFilterStatus, FlowRate, LeakDetection, FuelPumpStatus)
VALUES
    ('working', 75.5, 10.5, 'чистый', 50.0, false, 'Вкл.'),
    ('not working', 20.0, 50.0, 'загрезнен', 20.0, true, 'Выкл.');


INSERT INTO EngineStatus (status, rpm, temperature, voltage) VALUES
    ('working', 2500, 85.5, 12.3),
    ('not working', 0, 0.0, 0.0);

INSERT INTO CoolingSystemStatus (status, coolanttemperature, systempressure) VALUES
    ('working', 80.0, 1.5),
    ('overheating', 110.0, 2.0);

INSERT INTO GeneratorStatus (status, power, fuel, voltage) VALUES
    ('working', 150.0, 'дизель', 220.0),
    ('not working', 0.0, 'бензин', 0.0);
